In [ ]:
#Create a null vector of size 10 with fifth value as 5.

In [3]:
import numpy as np

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Create a vector with values 10 to 49

In [6]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Create a 3*3 matrix with values ranging from 0 to 8

In [7]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [ ]:
# Create a 10x10 array with random values and find the minimum and maximum values.

In [12]:
x = np.random.random((10,10))
x_min = x.min()
x_max = x.max()
print(x_min,x_max)

0.010647522949939203 0.9946146629901945


In [ ]:
#Create a random vector of size 30 and find the mean value.

In [13]:
y = np.random.random(30)
x = y.mean()
print(x)

0.44520640900063596
